# Generated by Django 5.0.2 on 2024-03-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_store_custo_last_na_e6a359_idx_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_2e448d_idx',
        ),
    ]
